name: ServerTap
main: io.servertap.PluginEntrypoint
version: 0.1.3
description: ServerTap is a REST API for Bukkit/Spigot/PaperMC Minecraft servers.
api-version: 1.14
softdepend:
  - Vault
  - PlaceholderAPI
