name: Build ServerTap

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Clean up artifacts
      run: mkdir artifacts && rm target/original-*.jar && cp target/*.jar artifacts/
    - uses: actions/upload-artifact@v1
      with:
        name: Release
        path: artifacts/*.jar
